"""Initial migration

Revision ID: c56a9abf809e
Revises: 
Create Date: 2026-05-22 19:23:04.926775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c56a9abf809e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'ai_model_runs', 'telemetry_payloads', ['payload_id'], ['payload_id'])
    op.create_foreign_key(None, 'analyst_feedback', 'telemetry_payloads', ['payload_id'], ['payload_id'])
    op.create_foreign_key(None, 'app_inventory_current', 'telemetry_payloads', ['last_seen_payload_id'], ['payload_id'])
    op.create_foreign_key(None, 'device_reports', 'telemetry_payloads', ['payload_id'], ['payload_id'])
    op.create_foreign_key(None, 'important_logs', 'telemetry_payloads', ['payload_id'], ['payload_id'])
    op.create_foreign_key(None, 'risk_assessments', 'telemetry_payloads', ['payload_id'], ['payload_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_assessments', type_='foreignkey')
    op.drop_constraint(None, 'important_logs', type_='foreignkey')
    op.drop_constraint(None, 'device_reports', type_='foreignkey')
    op.drop_constraint(None, 'app_inventory_current', type_='foreignkey')
    op.drop_constraint(None, 'analyst_feedback', type_='foreignkey')
    op.drop_constraint(None, 'ai_model_runs', type_='foreignkey')
    # ### end Alembic commands ###
